######################
# datasource setting #
######################
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/basicBoot
    password: '123'
  thymeleaf:
    cache: 'false'
  ######################
  # JPA setting #
  ######################
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
  ######################
  # jackson setting #
  ######################
  jackson:
    property-naming-strategy: SNAKE_CASE
##########################################################
# Detail Show JPA Query                                  #
# have to setting - Dev [true] - Prod [false] setting    #
##########################################################
decorator:
  datasource:
    p6spy:
      enable-logging: 'true'




