######################
# datasource setting #
######################
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/basicBoot
    password: '123'
  thymeleaf:
    cache: 'false'

##########################################################
# Detail Show JPA Query                                  #
# have to setting - Dev [true] - Prod [false] setting    #
##########################################################
decorator:
  datasource:
    p6spy:
      enable-logging: 'true'

######################
# JPA setting #
######################
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'