######################
# datasource setting #
######################
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/basicBoot
    password: '123'
  thymeleaf:
    cache: 'false'
  ######################
  # JPA setting #
  ######################
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
  ######################
  # jackson setting #
  ######################
  jackson:
    property-naming-strategy: SNAKE_CASE
  ######################
  # include OAuth #
  ######################
  profiles:
    include: oauth
  ############################
  ##Redis Setting
  ############################
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
  ############################
  ##Mail Setting
  ############################
  mail:
    host: smtp.gmail.com
    port: 587
    default:
      encoding: UTF-8
    username: dbwjdghman93@gmail.com
    password: jpzytlrpwmrfwfic
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

##########################################################
# Detail Show JPA Query                                  #
# have to setting - Dev [true] - Prod [false] setting    #
##########################################################
decorator:
  datasource:
    p6spy:
      enable-logging: 'true'
############################
##Setting Security Log Level
############################
logging:
  level:
      org:
        springframework:
          security:
            web: trace




