######################
# datasource setting #
######################
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/basicBoot
    password: '123'
